### ISSUE TITLE
`doFlash.sh` Crash on Restore Devices

### ISSUE THREAD

**Issue by lbussy** [brewpi-remix/brewpi-script-rmx#190]
Reported by IanJ on HBT: When restoring devices or settings (on Python 3.7.x) an assertion is raised:

```
Arduino program script started.
Traceback (most recent call last):
  File "/home/brewpi/updateFirmware.py", line 431, in <module>
    result = main()
  File "/home/brewpi/updateFirmware.py", line 426, in main
    result = updateFromGitHub(beta, doShield, userInput)
  File "/home/brewpi/updateFirmware.py", line 389, in updateFromGitHub
    result = programmer.programController(config, board, localFileName, {'settings': restoreSettings, 'devices': restoreDevices})
  File "/home/brewpi/programController.py", line 199, in programController
    return programmer.program(hexFile, restoreWhat)
  File "/home/brewpi/programController.py", line 236, in program
    self.parse_restore_settings(restoreWhat)
  File "/home/brewpi/programController.py", line 296, in parse_restore_settings
    if version.parse(self.versionNew) >= version.parse(self.versionOld): # Only restore settings on same or newer
  File "/home/brewpi/venv/lib/python3.7/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/home/brewpi/venv/lib/python3.7/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

The assertion is raised in two places:

https://github.com/brewpi-remix/brewpi-script-rmx/blob/e560efc9ad5d1447313df4a74624ea71dbb8b68d/programController.py#L296

https://github.com/brewpi-remix/brewpi-script-rmx/blob/e560efc9ad5d1447313df4a74624ea71dbb8b68d/programController.py#L300

**Comment by lbussy** [comment]
This is still an issue on Bullseye.

**Comment by lbussy** [comment]
This is related to #192 and changes brought in by Bullseye.
